### ISSUE TITLE
check for https instead of http

### ISSUE THREAD

**Issue by hfrick** [ropensci-review-tools/goodpractice#102]
rhub checks for canonical CRAN URLs including https but another URL with http slipped through

**Comment by katrinleinweber** [comment]
Would it be possible to test all `http` URLs, check whether they redirect to `https` and if yes: update the URL in the source file?

**Comment by gaborcsardi** [comment]
goodpractice does not currently modify the package, it just gives advice.

**Comment by katrinleinweber** [comment]
I know it doesn't. If that was a fundamental design decision and is not up for debate, my above question has been answered ;-)

**Comment by gaborcsardi** [comment]
> If that was a fundamental design decision

yes, it was.

**Comment by gaborcsardi** [comment]
sorry, closed accidentally

**Comment by mpadge** [comment]
rOpenSci has now taken over maintenance of this package, as part of which we're cleaning out old issues. The checks from {goodpractice} are incorporated within our own checking system, [{pkgcheck}](https://github.com/ropensci-review-tools/pkgcheck), which also includes the kinds of checks you describe, so I'll close this issue now. Thanks for the input.
