### ISSUE TITLE
Load custom checks/configuration from separate file

### ISSUE THREAD

**Issue by adfi** [ropensci-review-tools/goodpractice#113]
If a person/organisation has a substantial amount of custom checks it would be helpful to specify these in a separate file and then refer to that file when calling `gp()`. This could possibly be generalised to an overall configuration file (not sure what else would need configuring). (h/t @MrKriss )

**Comment by gaborcsardi** [comment]
Good idea. Maybe you can use the config package to load a yaml config file.

**Comment by mpadge** [comment]
rOpenSci has now taken over maintenance of this package, as part of which we're cleaning out old issues. The checks from {goodpractice} are incorporated within our own checking system, [{pkgcheck}](https://github.com/ropensci-review-tools/pkgcheck), which is readily extendible to all sorts of custom checks, so I'll close this issue now. Thanks for the input.
