### ISSUE TITLE
Detect old DOI resolver URLs

### ISSUE THREAD

**Issue by katrinleinweber** [ropensci-review-tools/goodpractice#120]
Many people ([also in the R community](https://github.com/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Akatrinleinweber+org%3Aropensci+doi)) still use the old `http://dx.doi.org/` resolver, although the DOI foundation set up [a new, secure one](https://www.doi.org/doi_handbook/3_Resolution.html#3.8) years ago. Yes, it's a bit ironic that they would change the URL of their service, but they redirect the old links.

In order to help adoption of the new recommendation, how about adding a function to this package, that detects them and suggests (or even applies) the necessary updates?

It would mostly affect references in ReadMe files, vignettes, etc.

**Comment by dougmet** [comment]
By extension for any common service for which we know there is https we could recommend that. So DOI is a great example. CRAN is another (see #102). There must be more.

**Comment by katrinleinweber** [comment]
arXiv.org, doi.acm.org are two I see every now and then.

**Comment by katrinleinweber** [comment]
Usethis decided against adding a function to produce canonical CRAN links: https://github.com/r-lib/usethis/issues/20

**Comment by mpadge** [comment]
rOpenSci has now taken over maintenance of this package, as part of which we're cleaning out old issues. The checks from {goodpractice} are incorporated within our own checking system, [{pkgcheck}](https://github.com/ropensci-review-tools/pkgcheck), which also includes the kinds of checks you describe, so I'll close this issue now. Thanks for the input.
