### ISSUE TITLE
Plans for CI integration akin to lintr/lintr-bot?

### ISSUE THREAD

**Issue by AdamSpannbauer** [ropensci-review-tools/goodpractice#126]
Are there plans to integrate with CI tools + a GitHub bot?

i.e. I think it would be valuable to have a bot like [lintr-bot](https://github.com/lintr-bot).  I would love to be able to specifically have a `cyclocomp` bot that could check/flag PRs that violate a complexity threshold.

**Comment by mpadge** [comment]
rOpenSci has now taken over maintenance of this package, as part of which we're cleaning out old issues. The checks from {goodpractice} are incorporated within our own checking system, [{pkgcheck}](https://github.com/ropensci-review-tools/pkgcheck), which also includes the kinds of checks you describe, so I'll close this issue now. Thanks for the input.
