### ISSUE TITLE
Make logo appear in Twitter cards

### ISSUE THREAD

**Issue by maelle** [ropensci-review-tools/goodpractice#127]
I think you need to

* create a pkgdown config file

* add the website url in it

```
url: https://t.co/0825I3oDHt
```

* then re-run `usethis::use_logo()` to get the image code to put in the README, that will contain the URL to the image this time.

**Comment by maelle** [comment]
To check the card you can use https://cards-dev.twitter.com/validator

**Comment by mpadge** [comment]
rOpenSci has now taken over maintenance of this package, as part of which we're cleaning out old issues. @maelle Is this issue still valid or relevant?

**Comment by maelle** [comment]
not the pkgdown part but it'd make sense to upload the logo under "social preview" in https://github.com/ropensci-review-tools/goodpractice/settings

**Comment by mpadge** [comment]
Thanks, done.
