### ISSUE TITLE
Date: "omit" advice vs. "no" warning

### ISSUE THREAD

**Issue by katrinleinweber** [ropensci-review-tools/goodpractice#128]
`goodpractice` recommends to `omit "Date" in DESCRIPTION.` but when trying `citation(…)` on after installing a package without that field, a warning appears: `no date field in DESCRIPTION file of package '…'` and the year is automatically inserted into the suggestion citation text / BibTeX.

Should these opposing advice maybe be squared by recommending to use only the year, or a note like `you can safely ignore the citation() warning about "no date filed"` be added?

**Comment by gaborcsardi** [comment]
I think `citation()` could use the release date of the package in this case. E.g. https://github.com/cran/goodpractice/blob/1755c716e56043d7c471eea6ca56c639cf6ec38c/DESCRIPTION#L34

Btw, you can also create a dedicated `CITATION` file, if there a package has a proper paper.

**Comment by katrinleinweber** [comment]
Ah, OK, thanks! `Date/Publication` is added automatically by CRAN, right? So the `no date field` warning would only appear only for the package developer.

**Comment by mpadge** [comment]
rOpenSci has now taken over maintenance of this package, as part of which we're cleaning out old issues. I'm pretty sure this has all been addressed in the meantime, so I'll close now. Thanks for the input.
