### ISSUE TITLE
'lintr::expect_lint_free()' fails when run by goodpractice

### ISSUE THREAD

**Issue by richelbilderbeek** [ropensci-review-tools/goodpractice#139]
[goodpractice is right](https://github.com/richelbilderbeek/mcbette/issues/22), but I am having trouble getting a clean result of `goodpractice`. 

If I have [a minimal package with only this test](https://travis-ci.org/richelbilderbeek/goodpractice_and_lintr_bug):

```
test_that("Package style", {
  lintr::expect_lint_free()
})
```

[Building on Travis CI passes fine](https://travis-ci.org/richelbilderbeek/goodpractice_and_lintr_bug/jobs/659537253#L819).

However, [when Travis script runs the next line,](https://travis-ci.org/richelbilderbeek/goodpractice_and_lintr_bug/jobs/659537253#L833) with the command `goodpractice::gp()`, I get 
[this log error message](https://travis-ci.org/richelbilderbeek/goodpractice_and_lintr_bug/jobs/659537253#L868):

```
It is good practice to

  ✖ checking tests ... Running ‘testthat.R’ ERROR Running the tests in

    ‘tests/testthat.R’ failed. Last 13 lines of output: >
    test_check("galb") ── 1. Error: Package style (@test-style.R#2)
    ────────────────────────────────── invalid 'path' argument
    Backtrace: 1. lintr::expect_lint_free() 2. lintr::lint_package(...)
    3. base::normalizePath(path, mustWork = FALSE) 4.
    base::path.expand(path) ══ testthat results
    ═══════════════════════════════════════════════════════════ [ OK: 0
    | SKIPPED: 0 | WARNINGS: 0 | FAILED: 1 ] 1. Error: Package style
    (@test-style.R#2) Error: testthat unit tests failed Execution
    halted
```

I expect the `goodpractice::gp()` test to work on Travis. When I run it locally, it also just works. 

I hope you enjoy my thorough bug report and I hope I can wish you good luck to fix this :+1:

**Comment by mpadge** [comment]
rOpenSci has now taken over maintenance of this package, as part of which we're cleaning out old issues. I'll presume the issue you describe is no longer relevant, and will close for now. Please feel free to re-open or comment further if that's not the case. Thanks for the input.
