### ISSUE TITLE
integrate with github repositories

### ISSUE THREAD

**Issue by LiNk-NY** [ropensci-review-tools/goodpractice#14]
A nice feature to add would be to directly check good practices on GitHub repositiories. The user would just need to enter:
(in pseudocode)

```
goodpractice::github_gp("username/repository")
```

**Comment by gaborcsardi** [comment]
👍

**Comment by mpadge** [comment]
@LiNk-NY rOpenSci has now taken over maintenance of this package, as part of which we're cleaning out old issues. The checks from {goodpractice} are incorporated within our own checking system, [{pkgcheck}](https://github.com/ropensci-review-tools/pkgcheck), which also includes the kinds of checks you describe, so I'll close this issue now. Thanks for the input.
