### ISSUE TITLE
Warning generated by UTF-8 strings

### ISSUE THREAD

**Issue by kamapu** [ropensci-review-tools/goodpractice#141]
UTF-8 encoding in data used as example by [`taxlist`](https://github.com/kamapu/taxlist) is causing a warning message by `goodpractice::gp()`, although UTF-8 encoding is already declared at DESCRIPTION:

>  - fix this R CMD check NOTE: Note: found 137 marked UTF-8 strings

There was a time, when I was getting this message by **R CMD check** but I have already solved the problem, thus I'm  wondering if this is a bug in `goodpractice`.

At the moment I'm testing the package in a Latin-1 locale as requested by CRAN with 0 errors, 0 notes, 0 warnings:

```r
devtools::build(...)
Sys.setenv(LANG="en_US.iso88591")
devtools::check_built(...)
```

**Comment by mpadge** [comment]
rOpenSci has now taken over maintenance of this package, as part of which we're cleaning out old issues. I presume this is no longer an issue, and will now close, but feel free to re-open and/or comment further if issue remains. Thanks for the input.
