### ISSUE TITLE
URL checks?

### ISSUE THREAD

**Issue by wlandau** [ropensci-review-tools/goodpractice#142]
Would [`urlchecker::url_check()`](https://github.com/r-lib/urlchecker) be in scope? I feel this would help prevent surprises when submitting to CRAN.

**Comment by mpadge** [comment]
rOpenSci has now taken over maintenance of this package, as part of which we're cleaning out old issues. The checks from {goodpractice} are incorporated within our own checking system, [{pkgcheck}](https://github.com/ropensci-review-tools/pkgcheck), which also includes the kinds of checks you describe, so I'll close this issue now. Thanks for the input.
