### ISSUE TITLE
CRAN Error

### ISSUE THREAD

**Issue by KarinaMarks** [ropensci-review-tools/goodpractice#157]
Dear maintainer,

Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_goodpractice.html>.

Apparently your package fails its checks in a strict Latin-1* locale, e.g. under Linux using LANG=en_US.iso88591 (see the debian-clang results).

Please correct before 2022-08-30 to safely retain your package on CRAN.

**Comment by KarinaMarks** [comment]
Commit fixes error for now b6c31d62ab3b0eca21224a307a51f55fcac2901f 

Temporary fix to keep package on CRAN, needs a more appropriate fix than skipping the test!

**Comment by mpadge** [comment]
Fixed with https://github.com/ropensci-review-tools/goodpractice/commit/904fa4d5c426aedc0f8f91a4add75edf0e97718b
