### ISSUE TITLE
Suggest using .Rbuildignore to help determine which files to examine

### ISSUE THREAD

**Issue by kwstat** [ropensci-review-tools/goodpractice#162]
The repository for my package (agridat) has a `data-raw` directory.
The `gp()` function is evaluating the code style in the `data-raw` directory, even though this will not be part of the submitted package.

Would it be possible for `gp()` to parse the .Rbuildignore file and skip the ignorable files?

**Comment by mpadge** [comment]
rOpenSci has now taken over maintenance of this package, as part of which we're cleaning out old issues. @kwstat Is this still an issue for you? If so, could you please produce a reproducible example?

**Comment by kwstat** [comment]
I am no longer using `goodpractice`.
