### ISSUE TITLE
Calling `gp()` on a loaded package could work better by temporarily unloading it

### ISSUE THREAD

**Issue by olivroy** [ropensci-review-tools/goodpractice#168]
It may be possible to use techniques used in pkgdown or usethis to achieve this.

```r
  pkgload::load_all(path, quiet = TRUE)
  withr::defer(pkgload::unload("templatepackage"), envir = env)
```

Reprex

```r
# in the goodpractice repo
devtools::load_all()
gp() # especially the covr check has issues.
```

I haven't tested fully, but locally if you have any package loaded with `load_all()`, it isn't really possible to run `gp()` and get all results due to some steps failing with Can't install a loaded package..

https://github.com/r-lib/pkgdown/blob/0e1352c92ff4ca8a3ba6e98863e710f14e18a632/R/pkgdown.R#L58-L77

I noticed this while working on #167 but came across this code in `local_pkgdown_template_pkg()`, so it may be possible to adapt it for goodpractice

**Comment by mpadge** [comment]
I donj't ever see any errors running `gp()` on a `load_all()` package. My guess is that this problem is specific to some particular configuration of OS, dev environment, whatever, and not a general issue? Any more details about how you think the problem can be reproduced?

**Comment by olivroy** [comment]
Oh, thanks for verifying. Yeah, I am on Windows... Maybe that's a reason why? Paths cannot be easily overwritten there. I will try coming up with something more concrete!

**Comment by olivroy** [comment]
turns out this was a covr issue https://github.com/r-lib/covr/pull/575. now fixed
