### ISSUE TITLE
Wish: test if all manual pages have examples

### ISSUE THREAD

**Issue by richelbilderbeek** [ropensci-review-tools/goodpractice#18]
I already see at #1 that this is on the wish list, but I hope to stimulate the development of this (I see all to often this slows everyone but the original developer down).

I even volunteer to help and I'd appreciate a pointer to the approach/packages you'd use.

**Comment by gaborcsardi** [comment]
Cool. I would look at `tools::parse_Rd` first, and create a preparation function that just parses all the docs into memory. Then write a check that checks all manual files.

**Comment by richelbilderbeek** [comment]
I am working on it at [the goodpracticeeighteen GitHub](https://github.com/richelbilderbeek/goodpracticeeighteen). Thanks to the tip it has been a breeze until now.

**Comment by richelbilderbeek** [comment]
I'd love to have my own Issue implemented now: I am missing documentation!

My questions are:

 * Where is it documented to add a new check?
 * How to let a new check display the failing files?

In [my fork](https://github.com/richelbilderbeek/goodpractice) I got it somewhat working, but the output does not display the failing files yet.

Here is my `prep` function:

```
# 'state' is a list that will be used by all tests. In this function,
#  you can add the data you need for your checkchk_ function
#' @include lists.R
#' @importFrom goodpracticeeighteen lint_package

PREPS$rf_filename <- function(state, path = state$path) {
  # Collect all .Rd filenames
  state$rd_filenames <- list.files(path = state$path, recursive = TRUE, pattern = "\\.Rd")
  # Collect all .Rd filenames that have no examples
  state$rd_filenames_without_examples <- state$rd_filenames[
    !goodpracticeeighteen::has_examples_in_rds(state$rd_filenames)
  ]
  # Return ?state
  state
}
```

Here is my `chk` function:

```
#' @include lists.R

CHECKS$man_must_have_examples <- make_check(
  # The description of the check
  description = "supply each function with an example",
  # The tag of the check, will be used for ...?
  tags = "man",
  # The preparation, preps value must match in 'prep_man_examples'
  preps = "rf_filename",
  # Text above the failed test
  gp = "each function must supply an example
        to demonstrate how it is used.
        With roxygen2, the @examples tag can be used",
  # Failed filenames
  check = function(state) {
    state$rd_filenames_without_examples
  }
)
```

Output:

```
each function must supply an example to demonstrate how it is used. With roxygen2, the @examples tag can be used
```

**Comment by mpadge** [comment]
rOpenSci has now taken over maintenance of this package, as part of which we're cleaning out old issues. The checks from {goodpractice} are incorporated within our own checking system, [{pkgcheck}](https://github.com/ropensci-review-tools/pkgcheck), which also includes the kinds of checks you describe, so I'll close this issue now. Thanks for the input.
