### ISSUE TITLE
Look at the rOpenSci packaging guidelines

### ISSUE THREAD

**Issue by gaborcsardi** [ropensci-review-tools/goodpractice#38]
We can probably implement a lot that as gp checks.

**Comment by kwstat** [comment]
Guidelines are here:
https://github.com/ropensci/onboarding/blob/master/packaging_guide.md

**Comment by mpadge** [comment]
rOpenSci has now taken over maintenance of this package, as part of which we're cleaning out old issues. The checks from {goodpractice} are incorporated within our own checking system, [{pkgcheck}](https://github.com/ropensci-review-tools/pkgcheck), which also includes the kinds of checks you describe, so I'll close this issue now. Thanks for the input.
