### ISSUE TITLE
Add devtools custom checks

### ISSUE THREAD

**Issue by maelle** [ropensci-review-tools/goodpractice#81]
E.g. checking vignettes have real titles.

**Comment by mpadge** [comment]
@maelle rOpenSci has now taken over maintenance of this package, as part of which we're cleaning out old issues. The checks from {goodpractice} are incorporated within our own checking system, [{pkgcheck}](https://github.com/ropensci-review-tools/pkgcheck), which also includes the kinds of checks you describe, so I'll close this issue now. Thanks for the input.
