### ISSUE TITLE
Test for CI

### ISSUE THREAD

**Issue by noamross** [ropensci-review-tools/goodpractice#86]
This is sort of meta, but a good check would be too look for CI infrastructure.  This could include

-   Checking for CI by looking for a `.travis.yml` or a `.circleci/config.yml`
-   Looking for a call to **covr** in those files
-   Looking for badges in the package README
-   One could even ping the service APIs to check on package status on the services as well - there would be enough info in the badge URLs.

**Comment by mpadge** [comment]
rOpenSci has now taken over maintenance of this package, as part of which we're cleaning out old issues. The checks from {goodpractice} are incorporated within our own checking system, [{pkgcheck}](https://github.com/ropensci-review-tools/pkgcheck), which also includes the kinds of checks you describe, so I'll close this issue now. Thanks for the input.
