### ISSUE TITLE
Test for code of conduct

### ISSUE THREAD

**Issue by noamross** [ropensci-review-tools/goodpractice#87]
This one is pretty easy, but the language should encourage people not to just add a CoC but to read it carefully and consider how they will use/enforce it.

**Comment by mpadge** [comment]
rOpenSci has now taken over maintenance of this package, as part of which we're cleaning out old issues. The checks from {goodpractice} are incorporated within our own checking system, [{pkgcheck}](https://github.com/ropensci-review-tools/pkgcheck), which also includes the kinds of checks you describe, so I'll close this issue now. Thanks for the input.
